# Generated by Django 6.0.1 on 2026-01-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
