# Generated by Django 6.0.1 on 2026-01-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0002_todoitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(choices=[(3, '高'), (2, '中'), (1, '低')], default=2),
        ),
    ]
